@startuml

package presentation {
    package view {
        package page {
            class CustomPage
        }
        package widget {
            class CustomWidget
        }
    }
}

package notifyer {
    class CustomNotifyer
}

package application {
    package model {
        class CustomModel<<freezed>>
    }
    class PersonAppService
    class TagAppService
}

package domain {
    package person {
        package anniversary {
            class Anniversary<<JsonSerializable>>
            interface IAnniversaryFactory
        }
        package contact {
            class Contact<<JsonSerializable>>
            interface IContactFactory
        }
        class Person<<JsonSerializable>>
        interface IPersonFactory
        interface IPersonRepository
    }
    package tag {
        class Tag
        class TagService
        interface ITagFactory
        interface ITagRepository
    }
}

package infrastructure {
    package "anniversary " {
        class AnniversaryFactory
    }
    package "contact " {
        class ContactFactory
    }
    package "person " {
        class PersonFactory
        class PersonRepository
    }
    package "tag " {
        class TagFacotory
        class TagRepository
    }
    interface LocalDataSource
}

package datasource {
    class AppDatabase
    class AnniversaryTable
    class ContactTable
    class TagTable
    class PersonTable
    class RegistedTagTable
    abstract DatabaseWrapper
    interface ITable
}

' view
CustomPage -- CustomWidget

' view - notifyer
CustomWidget ..> CustomNotifyer

' notifyer - application
CustomNotifyer ..> CustomModel

' application
CustomModel <-- TagAppService : create
CustomModel <-- PersonAppService : create

' application - domain
TagAppService ..> TagService
PersonAppService --> Person

' domain
Anniversary -- IAnniversaryFactory
Contact -- IContactFactory
Person *.. Anniversary
Person *.. Contact
Person -- IPersonFactory
Person -- IPersonRepository
TagService ..> Tag
TagService ..> ITagFactory
TagService ..> ITagRepository


' domain - infrastructure
IAnniversaryFactory <|.. AnniversaryFactory
IContactFactory <|.. ContactFactory
ITagFactory <|.. TagFacotory
ITagRepository <|.. TagRepository
IPersonFactory <|.. PersonFactory
IPersonRepository <|.. PersonRepository

' infrastructure
TagRepository ..> LocalDataSource
PersonRepository ..> LocalDataSource

' infrastructure - datasource
LocalDataSource <|-- DatabaseWrapper

' datasource
DatabaseWrapper <|-- AppDatabase
DatabaseWrapper "1" *..> "*" ITable
ITable <|.. AnniversaryTable
ITable <|.. ContactTable
ITable <|.. TagTable
ITable <|.. PersonTable
ITable <|.. RegistedTagTable

@enduml