@startuml

package view {
    package page {
        class FriendDetail
        class FriendEditPage
        class FriendListPage
    }

    package component {
        class FriendListView
        class FriendBasicInfoEditForm
        class EditableAnniversaryTile
        class EditableContactTile
    }
}

package viewModel {
    class FriendListViewModel
    class FriendBasicInfoEditViewModel
    class EditableAnniversaryViewModel
    class EditableContactViewModel
}

package model {
    class FriendBasicInfo<<freezed>>
    class EditableAnniversary<<freezed>>
    class EditableContact<<freezed>>
}


package repository {
    interface FriendRepository
    class FriendRepositoryByLocalDatabase
}

package entity {
    class Anniversary<<freezed>>
    class Contact<<freezed>>
    class Friend<<freezed>>
}

package infrastructure {
    package local {
        class AnniversaryTable
        class AppDatabase
        class ContactTable
        class FriendTable
        interface IDatabaseProvider
        interface ITable
    }
}

FriendListView ..> FriendListViewModel

FriendListPage ..> FriendListView
FriendEditPage ..> FriendBasicInfoEditForm
FriendEditPage ..> EditableAnniversaryTile
FriendEditPage ..> EditableContactTile

FriendBasicInfoEditForm ..> FriendBasicInfoEditViewModel
EditableAnniversaryTile ..> EditableAnniversaryViewModel
EditableContactTile ..> EditableContactViewModel

FriendBasicInfoEditViewModel ..> FriendBasicInfo
EditableAnniversaryViewModel ..> EditableAnniversary
EditableContactViewModel ..> EditableContact

FriendBasicInfo ..> Friend
EditableAnniversary ..> Anniversary
EditableContact ..> Contact

Friend o-left- Anniversary
Friend o- Contact

Friend <-- FriendRepository

FriendRepository <|.. FriendRepositoryByLocalDatabase

FriendRepositoryByLocalDatabase --> IDatabaseProvider

ITable <|-- AnniversaryTable
ITable <|-- ContactTable
ITable <|-- FriendTable
AppDatabase "1" o-- "*" ITable
IDatabaseProvider <|-- AppDatabase

@enduml