@startuml
hide circle

json anniversaries {
    "PK": "anniversary_id",
    "FK": "person_id",
    "": ["name", "date"]
}
json contacts {
    "PK": "contact_id",
    "FK": "person_id",
    "": ["name", "method", "value"]
}
json notifications {
    "PK": "notification_id",
    "FK": "anniversary_id"
}
json tags {
    "PK": "tag_id",
    "": "name"
}
json persons {
    "PK": "person_id",
    "": ["name", "nickname", "icon", "created_at", "updated_at"]
}
json registed_tags {
    "FK": ["person_id", "tag_id"]
}

anniversaries ||--|| notifications
persons ||--o{ anniversaries
persons ||--o{ contacts
persons ||--o{ registed_tags
registed_tags ||--|| tags

@enduml