@startuml
hide circle

json anniversaries {
    "PK": "id",
    "FK": "person_id",
    "": ["name", "date", "created_at", "updated_at"]
}
json contacts {
    "PK": "id",
    "FK": "person_id",
    "": ["name", "method", "value", "created_at", "updated_at"]
}
json notifications {
    "PK": "id",
    "FK": "anniversary_id",
    "": "interval_days"
}
json tags {
    "PK": "id",
    "": "name"
}
json persons {
    "PK": "id",
    "": ["name", "nickname", "icon", "created_at", "updated_at"]
}
json registed_tags {
    "FK": ["person_id", "tag_id"]
}

anniversaries ||--o{ notifications
persons ||--o{ anniversaries
persons ||--o{ contacts
persons ||--o{ registed_tags
registed_tags ||--|| tags

@enduml