@startuml
hide circle

json anniversaries {
    "PK|FK": "person_id",
    "PK": "name",
    "": "date"
}
json contacts {
    "PK|FK": "person_id",
    "PK": [
        "name",
        "method"
    ],
    "": "value"
}
json persons {
    "PK": "person_id",
    "": [
        "name",
        "nickname",
        "icon",
        "created_at",
        "updated_at"
    ]
}
json registed_tags {
    "PK|FK": [
        "person_id",
        "tag_name"
    ]
}
json tags {
    "PK": "name"
}

persons ||--o{anniversaries
persons ||--o{contacts
persons ||--o{registed_tags
registed_tags ||--|| tags

@enduml